#!/usr/bin/env python3

import sys
import subprocess

commands = dict()

commands["github"] = "https://github.com"
commands["katie"] = "https://katie.luther.edu"
commands["chem"] = "https://app.101edu.co/"
commands["mygit"] = "https://github.com/alexdikelsky"
commands["stack"] = "stackoverflow.com"
commands["search"] = "https://www.ecosia.org/?c=en"
commands["crates"] = "crates.io"
commands["ctan"] = "https://ctan.org/pkg?lang=en"
commands["desmos"] = "https://www.desmos.com/calculator"
commands["period"] = "https://en.wikipedia.org/wiki/Periodic_table#Overview"
commands["luther"] = "https://www.luther.edu"
commands["cal"] = "https://www.luther.edu/registrar/calendar/"


def run(n=""):
    if n in commands:
        return commands[n]
    else:
        return ""

if len(sys.argv) < 2:
    subprocess.call("firefox", shell=True)
else:
    site_name = (run(sys.argv[1]))
    subprocess.call("firefox " + site_name, shell=True)
